import { useEffect, useState } from "react";
import { apiUrl } from "./runtime";

type Notice = (notice: { type: "error" | "success" | "info"; text: string }) => void;
interface Overview { users: { total?: number; free_users?: number; pro_users?: number }; revenue_inr: number; subscriptions: { status: string; count: number }[]; daily_signups: { day: string; count: number }[]; top_countries: { country: string; count: number }[]; processing_usage: { event_type: string; amount: number }[]; analytics: { mrr_inr: number; arr_inr: number; conversion_rate: number; churn_rate: number } }

export function AdminView({ setNotice }: { setNotice: Notice }) {
  const [data, setData] = useState<Overview | null>(null);
  useEffect(() => { fetch(apiUrl("/api/admin/overview"), { credentials: "include", headers: { "X-CSRF-Token": sessionStorage.getItem("clipforge_csrf") || "" } }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.detail || "Could not load admin dashboard."); return body as Overview; }).then(setData).catch((error) => setNotice({ type: "error", text: error instanceof Error ? error.message : "Could not load admin dashboard." })); }, []);
  if (!data) return <div className="page-content generic-page"><div className="empty-panel">Loading admin dashboard…</div></div>;
  return <div className="page-content generic-page"><div className="generic-head"><div><span className="eyebrow">ADMIN / OPERATIONS</span><h1>Business dashboard</h1><p>Aggregated account, subscription, revenue, and local-processing metrics.</p></div><span className="free-badge">ADMIN ONLY</span></div><div className="billing-summary-grid"><div className="billing-summary-card"><span>Total users</span><strong>{data.users.total || 0}</strong><small>{data.users.free_users || 0} Free · {data.users.pro_users || 0} Pro</small></div><div className="billing-summary-card"><span>Revenue captured</span><strong>₹{data.revenue_inr.toLocaleString("en-IN")}</strong><small>Provider-confirmed payments</small></div><div className="billing-summary-card"><span>MRR / ARR</span><strong>₹{data.analytics.mrr_inr.toLocaleString("en-IN")}</strong><small>₹{data.analytics.arr_inr.toLocaleString("en-IN")} annualized</small></div><div className="billing-summary-card"><span>Conversion</span><strong>{data.analytics.conversion_rate}%</strong><small>Churn {data.analytics.churn_rate}%</small></div></div><section className="billing-table-panel"><div className="section-heading simple"><div><h2>Subscription statuses</h2><p>Counts from the local billing ledger.</p></div></div><div className="suggested-tags">{data.subscriptions.map((item) => <span key={item.status}>{item.status}: {item.count}</span>)}</div></section><section className="billing-table-panel"><div className="section-heading simple"><div><h2>Usage and countries</h2><p>Only product metrics needed for operations are retained.</p></div></div><div className="suggested-tags">{data.processing_usage.map((item) => <span key={item.event_type}>{item.event_type}: {item.amount}</span>)}{data.top_countries.map((item) => <span key={item.country}>{item.country}: {item.count}</span>)}</div></section></div>;
}
