import { useEffect, useState } from "react";
import { cancelBillingSubscription, getBillingDashboard } from "./socialApi";
import { apiUrl } from "./runtime";

type Notice = (notice: { type: "error" | "success" | "info"; text: string }) => void;

export function BillingView({ setNotice }: { setNotice: Notice }) {
  const [data, setData] = useState<{ subscription: Record<string, unknown> | null; payments: Record<string, unknown>[]; invoices: Record<string, unknown>[]; provider: { configured: boolean; provider: string } } | null>(null);
  const [busy, setBusy] = useState(false);
  const load = async () => { try { setData(await getBillingDashboard()); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Could not load billing dashboard." }); } };
  useEffect(() => { void load(); }, []);
  const cancel = async () => { if (!window.confirm("Cancel renewal at the end of the current billing period?")) return; setBusy(true); try { const result = await cancelBillingSubscription(true); setNotice({ type: "success", text: result.message }); await load(); } catch (error) { setNotice({ type: "error", text: error instanceof Error ? error.message : "Could not cancel the subscription." }); } finally { setBusy(false); } };
  const subscription = data?.subscription;
  return <div className="page-content generic-page"><div className="generic-head"><div><span className="eyebrow">ACCOUNT / BILLING</span><h1>Billing dashboard</h1><p>Payment records and subscription state come from verified server-side provider events.</p></div><span className="free-badge">{data?.provider.configured ? data.provider.provider.toUpperCase() : "NOT CONFIGURED"}</span></div><div className="billing-summary-grid"><div className="billing-summary-card"><span>Current plan</span><strong>{subscription?.plan_id === "pro" ? "Pro" : "Free"}</strong><small>{subscription?.status ? String(subscription.status) : "No active subscription"}</small></div><div className="billing-summary-card"><span>Status</span><strong>{String(subscription?.status || "free").toUpperCase()}</strong><small>{subscription?.renewal_at ? `Renewal ${new Date(String(subscription.renewal_at)).toLocaleDateString()}` : "No renewal scheduled"}</small></div><div className="billing-summary-card"><span>Provider</span><strong>{data?.provider.provider || "none"}</strong><small>{data?.provider.configured ? "Server-side verification enabled" : "No payment can be taken"}</small></div></div>{subscription?.plan_id === "pro" && <div className="billing-actions"><button className="secondary-button" disabled={busy || String(subscription.status) === "cancelled"} onClick={() => void cancel()}>{busy ? "Updating…" : "Cancel at renewal"}</button></div>}<section className="billing-table-panel"><div className="section-heading simple"><div><h2>Payment history</h2><p>Captured payments only; failed attempts remain provider-side until recorded.</p></div></div>{data?.payments.length ? <div className="billing-table">{data.payments.map((payment) => <div className="billing-row" key={String(payment.id)}><div><strong>{String(payment.provider_payment_id)}</strong><span>{String(payment.method || "Provider checkout")}</span></div><b>₹{Number(payment.amount || 0).toLocaleString("en-IN")}</b><span>{String(payment.status)}</span></div>)}</div> : <div className="empty-panel">No verified payments yet.</div>}</section><section className="billing-table-panel"><div className="section-heading simple"><div><h2>Invoices</h2><p>Download an invoice after a verified payment.</p></div></div>{data?.invoices.length ? <div className="billing-table">{data.invoices.map((invoice) => <div className="billing-row" key={String(invoice.id)}><div><strong>{String(invoice.invoice_number)}</strong><span>{new Date(String(invoice.invoice_date)).toLocaleDateString()}</span></div><b>₹{Number(invoice.amount || 0).toLocaleString("en-IN")}</b><a className="small-button" href={apiUrl(`/api/billing/invoices/${invoice.id}/download`)}>Download PDF</a></div>)}</div> : <div className="empty-panel">No invoices yet.</div>}</section><div className="rights-note"><span>ⓘ</span><p>ClipForge never activates Pro based only on a browser callback. The provider signature and captured payment/webhook state must be verified on the server.</p></div></div>;
}
